### ISSUE TITLE
SMB and NFS plugins status?

### ISSUE THREAD

**Issue by johan-sv** [olljanat/csi-plugins-for-docker-swarm#17]
Both issues in their respective repository have been closed but I can't find any more information about them. What is their status?

**Comment by olljanat** [comment]
Valid question. Both plugins should works fine when build with scripts shared in here or when using versions provided by me https://hub.docker.com/r/ollijanatuinen/swarm-csi-smb and https://hub.docker.com/r/ollijanatuinen/swarm-csi-nfs

Just make sure that that you are using latest Docker versions so bugs mentioned in here do not apply anymore.

When it comes to getting support for these merged to upstream, as expected those who are working with Kubernetes do not care about Swarm so probably bringing these to moby should be considered (like @neersighted proposed in https://github.com/olljanat/csi-plugins-for-docker-swarm/issues/14#issuecomment-1435057640 )

PS. A lot of have changed since I started this initiative so cannot promise to be contributing to this anytime soon.

**Comment by Thyran** [comment]
Unfortunately I was not able to replicate the success mentioned with these plugins. As of docker version 27.1.2 all cluster volumes get stuck in "pending creation". Regarding the nfs-plugin apparently this is due to a malformed http1.x response but I can not explain what exactly would be the problem. My best guess is that the system has changed so much, that it is no longer working anymore.

Have you been able to get it working recently by any means?

**Comment by olljanat** [comment]
@Thyran I would recommend to check what is latest version which works are report that as bug to moby/moby.

I haven’t used these after they was posted in here because there is no official support for CSI plugin which I would need.

Also I have came to conclusion that Swarm (like K8s cluster) is still single point of failure so it is better to run only stateless applications in there and use standalone Docker hosts to run anything which need persistent storage. Then application layer is responsible to implement high availability and as long those are running in different datacenters there is no any single point of failures left and setup is an actually much simpler than with Swarm/K8s. But that sets some new requirements for network layer which why I recently built [docker-bgp-lb](https://github.com/olljanat/docker-bgp-lb)

**Comment by Thyran** [comment]
@olljanat Thanks to your input I was able to specifically locate a version that works. Namely docker version 26.0.0 seems to have no issues, so thanks for your help :). There are issues open on the NFS CSI repo addressing docker version 26.1 where it apparently broke due to a faulty implementation I would assume. Something about the plugin missing the PluginAddr Interface, it did not get fixed in any later version as the latest docker versions still run into the same issue.
I hope that this will eventually get fixed but I am still relieved that it has probably nothing to do with your adaptation of the plugin.
Seems like we will have to wait a bit longer until the csi volumes can be used consistently in future verrsions.

 Edit: the issue I was reffereing to was not on the NFS CSI repo, instead: https://github.com/moby/moby/issues/48133

**Comment by olljanat** [comment]
> Edit: the issue I was reffereing to was not on the NFS CSI repo, instead: https://github.com/moby/moby/issues/48133

That looks to be fixed now and fix will be released as part of 27.4.0 afaiu.

Will close this one but feel free to comment in case it does not fix the issue.

**Comment by olljanat** [comment]
Reopening because issue looks to be still present in 27.4.0-rc2: https://github.com/moby/moby/issues/48133#issuecomment-2500843792

**Comment by olljanat** [comment]
FYI, Now it is finally fixed in Docker [v28.2.0-rc.1](https://github.com/moby/moby/releases/tag/v28.2.0-rc.1) version and my PR https://github.com/moby/moby/pull/49983 should avoid this and similar issues coming back after it is merged so closing this now.
